---
version: 2

# Build settings
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

# Python settings
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# MkDocs settings
mkdocs:
  configuration: mkdocs.yml
