site_name: Laboratory protocols
site_url: https://darosio.github.io/mkprotocols
repo_url: https://github.com/darosio/mkprotocols
repo_name: darosio/mkprotocols
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.progress  # Conflict with pdf export
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.prune
    - toc.follow
    - content.code.copy
    - content.code.annotations
  font:
    text: Roboto #IBM Plex Serif
    code: Space Mono
  logo: assets/android-chrome-512x512.png
  favicon: assets/favicon-32x32.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Introduction: README.md
  - Protocols:
      - Titration: protocols/Titration_in_cells.md
  - HowTo:
      - Development: development.md

plugins:
  - search
  - pdf-export
